'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=s=>{if(!s)return'';const [y,m,d]=s.split('-');return `${d}/${m}/${y}`};
const safe=s=>String(s||'').replace(/[<>]/g,'');
let db,currentId=null,editingId=null,tempAttachments=[],tempSignature=null,deferredPrompt=null,previewReceiptId=null;
let state={meta:{placeDate:'',period:'',responsible:'ANDRES GUTIERREZ BECERRA',area:'OPERACIONES',position:'COPILOTO',aircraft:'HK4900',cardNumber:'',initialBalance:1000000,secondDeposit:0,observations:''},movements:[],updatedAt:new Date().toISOString()};
if(window.pdfjsLib) pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';

function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2400)}
function openDB(){return new Promise((ok,fail)=>{const r=indexedDB.open('SIS_Caja_Menor',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('boxes'))d.createObjectStore('boxes',{keyPath:'id'});if(!d.objectStoreNames.contains('draft'))d.createObjectStore('draft');};r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>fail(r.error)})}
function put(store,key,val){return new Promise((ok,fail)=>{const tx=db.transaction(store,'readwrite'),os=tx.objectStore(store),r=key===null?os.put(val):os.put(val,key);r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})}
function get(store,key){return new Promise((ok,fail)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})}
function getAll(store){return new Promise((ok,fail)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error)})}
function del(store,key){return new Promise((ok,fail)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(key);r.onsuccess=ok;r.onerror=()=>fail(r.error)})}
async function persistDraft(){state.updatedAt=new Date().toISOString();await put('draft','current',state)}
function totals(){const spent=state.movements.reduce((a,b)=>a+(+b.amount||0),0),initial=(+state.meta.initialBalance||0)+(+state.meta.secondDeposit||0);return{spent,balance:initial-spent,initial}}
function syncMetaToForm(){Object.keys(state.meta).forEach(k=>{const el=$('#'+k);if(el)el.value=state.meta[k]??''});$('#boxTitle').textContent=`${state.meta.aircraft||'Sin aeronave'} · ${state.meta.period||'Caja actual'}`}
function syncMetaFromForm(){Object.keys(state.meta).forEach(k=>{const el=$('#'+k);if(el)state.meta[k]=el.type==='number'?+el.value:el.value});persistDraft();render()}
function render(){const t=totals();$('#mInitial').textContent=money(t.initial);$('#mSpent').textContent=money(t.spent);$('#mBalance').textContent=money(t.balance);$('#mCount').textContent=state.movements.length;$('#boxTitle').textContent=`${state.meta.aircraft||'Sin aeronave'} · ${state.meta.period||'Caja actual'}`;renderMovements()}
function movementStatus(x){
  const isReceipt=x.support==='Recibo de Caja';
  const receiptOk=isReceipt;
  const signOk=!isReceipt||!!x.signature;
  const supportOk=isReceipt||!!x.attachments?.length;
  const complete=receiptOk&&signOk&&supportOk || (!isReceipt&&supportOk);
  return{isReceipt,receiptOk,signOk,supportOk,complete};
}
function renderMovements(){
  const box=$('#movementList'),filter=$('#filter').value;
  let arr=[...state.movements].sort((a,b)=>(a.date+a.createdAt).localeCompare(b.date+b.createdAt));
  if(filter==='pending')arr=arr.filter(x=>!movementStatus(x).complete);
  if(filter==='receipt')arr=arr.filter(x=>x.support==='Recibo de Caja');
  if(filter==='invoice')arr=arr.filter(x=>x.support==='Factura');
  box.innerHTML='';
  if(!arr.length){box.innerHTML='<p class="muted">Todavía no hay movimientos en esta vista.</p>';return}
  for(const x of arr){
    const s=movementStatus(x),d=document.createElement('article');
    d.className=`movement${s.complete?' complete':''}`;
    const idLabel=/nit|rut/i.test(x.idType||'')?'NIT':'CC';
    d.innerHTML=`<div><div class="title">${safe(x.detail||x.category)}</div><div class="person">${safe(x.thirdParty||'Sin tercero')}</div><div class="idline">${x.idNumber?`${idLabel} ${safe(x.idNumber)} · `:''}${fmtDate(x.date)} · ${safe(x.city)}</div><div class="meta">${safe(x.support)} · ${safe(x.category)}</div><div class="badges">${s.isReceipt?`<span class="badge ok">Recibo</span><span class="badge ${s.signOk?'ok':'warn'}">${s.signOk?'Firma lista':'Falta firma'}</span>`:`<span class="badge ${s.supportOk?'ok':'warn'}">${s.supportOk?'Soporte listo':'Falta soporte'}</span>`}${s.complete?'<span class="badge complete">✓ Movimiento completo</span>':''}</div></div><div class="amount">${money(x.amount)}</div><div class="actions">${s.isReceipt?'<button data-receipt class="primary-action">📄 Recibo</button><button data-sign>✍ Firmar</button>':'<button data-scan>📷 Escanear</button>'}<button data-edit>Editar</button><button data-copy>Duplicar</button><button data-delete class="danger">Eliminar</button></div>`;
    d.querySelector('[data-edit]').onclick=()=>openExpense(x.id);
    d.querySelector('[data-receipt]')?.addEventListener('click',()=>openReceiptPreview(x.id));
    d.querySelector('[data-sign]')?.addEventListener('click',()=>openExpenseAction(x.id,'sign'));
    d.querySelector('[data-scan]')?.addEventListener('click',()=>openExpenseAction(x.id,'scan'));
    d.querySelector('[data-copy]').onclick=()=>{const c=structuredClone(x);c.id=uid();c.createdAt=new Date().toISOString();c.signature=null;state.movements.push(c);persistDraft();render();toast('Movimiento duplicado')};
    d.querySelector('[data-delete]').onclick=async()=>{if(confirm('¿Eliminar este movimiento?')){state.movements=state.movements.filter(m=>m.id!==x.id);await persistDraft();render()}};
    box.appendChild(d)
  }
}

function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='historyView')renderHistory()}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));

function resetExpense(){editingId=null;tempAttachments=[];tempSignature=null;$('#expenseTitle').textContent='Añadir gasto';$('#eDate').value=today();$('#eCity').value=state.movements.at(-1)?.city||'';$('#eSupport').value='Recibo de Caja';$('#eCategory').value='Transporte';$('#eDetail').value='';$('#eThirdParty').value='';$('#eIdType').value='Cédula de Ciudadanía';$('#eIdNumber').value='';$('#eAmount').value='';renderAttachmentPreview();renderSignatureStatus()}
function openExpense(id=null){resetExpense();if(id){const x=state.movements.find(m=>m.id===id);if(!x)return;editingId=id;$('#expenseTitle').textContent='Editar gasto';$('#eDate').value=x.date;$('#eCity').value=x.city;$('#eSupport').value=x.support;$('#eCategory').value=x.category;$('#eDetail').value=x.detail;$('#eThirdParty').value=x.thirdParty;$('#eIdType').value=x.idType;$('#eIdNumber').value=x.idNumber;$('#eAmount').value=x.amount;tempAttachments=structuredClone(x.attachments||[]);tempSignature=x.signature||null;renderAttachmentPreview();renderSignatureStatus()}$('#expenseModal').classList.remove('hidden')}
$('#quickAdd').onclick=()=>openExpense();$('#closeExpense').onclick=()=>$('#expenseModal').classList.add('hidden');
function openExpenseAction(id,action){openExpense(id);setTimeout(()=>{if(action==='sign')$('#signReceipt').click();if(action==='scan')$('#eFiles').click()},180)}
$$('.quick-types button').forEach(b=>b.onclick=()=>{$('#eCategory').value=b.dataset.cat;$('#eDetail').value=b.dataset.desc});
function renderSignatureStatus(){$('#signatureStatus').textContent=$('#eSupport').value==='Recibo de Caja'?(tempSignature?'Firma guardada para este recibo.':'Este recibo aún no tiene firma.'):'La firma solo aplica a Recibos de Caja.'}
$('#eSupport').onchange=renderSignatureStatus;
async function fileToDataURL(file){return new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=fail;r.readAsDataURL(file)})}
async function imageCompressed(file){const src=await fileToDataURL(file);return new Promise((ok,fail)=>{const im=new Image();im.onload=()=>{const max=1800,ratio=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*ratio);c.height=Math.round(im.height*ratio);c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.82))};im.onerror=fail;im.src=src})}
async function pdfPages(file){const data=await file.arrayBuffer(),pdf=await pdfjsLib.getDocument({data}).promise,pages=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),vp=p.getViewport({scale:1.7}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;pages.push(c.toDataURL('image/jpeg',.82))}return pages}
$('#eFiles').onchange=async e=>{for(const f of [...e.target.files]){toast(`Procesando ${f.name}`);const pages=f.type==='application/pdf'?await pdfPages(f):[await imageCompressed(f)];tempAttachments.push({name:f.name,type:f.type,pages})}renderAttachmentPreview();e.target.value=''};
function renderAttachmentPreview(){const box=$('#attachmentPreview');box.innerHTML='';tempAttachments.forEach((a,i)=>{const d=document.createElement('div');d.className='attachment-card';d.innerHTML=`<img src="${a.pages[0]}"><small>${safe(a.name)}${a.pages.length>1?` (${a.pages.length})`:''}</small><button class="danger">Quitar</button>`;d.querySelector('button').onclick=()=>{tempAttachments.splice(i,1);renderAttachmentPreview()};box.appendChild(d)})}
$('#saveExpense').onclick=async()=>{const x={id:editingId||uid(),date:$('#eDate').value,city:$('#eCity').value.trim(),support:$('#eSupport').value,category:$('#eCategory').value,detail:$('#eDetail').value.trim(),thirdParty:$('#eThirdParty').value.trim(),idType:$('#eIdType').value,idNumber:$('#eIdNumber').value.trim(),amount:+$('#eAmount').value||0,attachments:tempAttachments,signature:$('#eSupport').value==='Recibo de Caja'?tempSignature:null,createdAt:editingId?(state.movements.find(m=>m.id===editingId)?.createdAt||new Date().toISOString()):new Date().toISOString()};if(!x.date||!x.city||!x.detail||!x.amount)return alert('Complete fecha, ciudad, detalle y valor.');const isTaxi=x.category==='Transporte'&&/^taxi\b/i.test(x.detail);if(isTaxi&&(!x.thirdParty||!x.idNumber))return alert('Para gastos de taxi debe registrar el nombre del conductor y su número de cédula.');if(x.support==='Recibo de Caja'&&(!x.thirdParty||!x.idNumber))return alert('Todo recibo de caja debe incluir el nombre del beneficiario y su número de identificación.');if(editingId)state.movements=state.movements.map(m=>m.id===editingId?x:m);else state.movements.push(x);await persistDraft();$('#expenseModal').classList.add('hidden');render();toast('Gasto guardado')};

// Firma táctil por recibo
const sig=$('#signatureCanvas'),ctx=sig.getContext('2d');let drawing=false,last=null;
function resizeSig(){const rect=sig.getBoundingClientRect(),scale=devicePixelRatio||1;sig.width=rect.width*scale;sig.height=220*scale;ctx.setTransform(scale,0,0,scale,0,0);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.strokeStyle='#111';ctx.fillStyle='#fff';ctx.fillRect(0,0,rect.width,220);if(tempSignature){const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,rect.width,220);im.src=tempSignature}}
function pt(e){const r=sig.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:t.clientX-r.left,y:t.clientY-r.top}}
function start(e){e.preventDefault();drawing=true;last=pt(e)}function move(e){if(!drawing)return;e.preventDefault();const p=pt(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p}function end(){drawing=false}
['pointerdown','touchstart'].forEach(n=>sig.addEventListener(n,start,{passive:false}));['pointermove','touchmove'].forEach(n=>sig.addEventListener(n,move,{passive:false}));['pointerup','pointercancel','touchend'].forEach(n=>sig.addEventListener(n,end));
$('#signReceipt').onclick=()=>{if($('#eSupport').value!=='Recibo de Caja')return alert('La firma se usa únicamente para Recibo de Caja.');$('#signatureModal').classList.remove('hidden');requestAnimationFrame(resizeSig)};$('#closeSignature').onclick=()=>$('#signatureModal').classList.add('hidden');$('#clearSignature').onclick=()=>{tempSignature=null;resizeSig()};$('#confirmSignature').onclick=()=>{tempSignature=sig.toDataURL('image/png');$('#signatureModal').classList.add('hidden');renderSignatureStatus();toast('Firma guardada')};

$('#saveBox').onclick=()=>{syncMetaFromForm();toast('Datos guardados')};
$('#newBox').onclick=async()=>{if(!confirm('¿Iniciar una caja nueva? La caja actual debe guardarse en historial si desea conservarla.'))return;currentId=null;state={meta:{placeDate:'',period:'',responsible:'ANDRES GUTIERREZ BECERRA',area:'OPERACIONES',position:'COPILOTO',aircraft:'HK4900',cardNumber:'',initialBalance:1000000,secondDeposit:0,observations:''},movements:[],updatedAt:new Date().toISOString()};syncMetaToForm();await persistDraft();render();showView('homeView')};
async function archiveCurrent(){syncMetaFromForm();const id=currentId||uid(),payload={...structuredClone(state),id};currentId=id;await put('boxes',null,payload);toast('Caja guardada en historial');return payload}

// Excel oficial basado en la plantilla entregada
function excelSerial(s){const d=new Date(`${s}T00:00:00`);return (d-Date.UTC(1899,11,30))/86400000}
$('#exportExcel').onclick=async()=>{try{syncMetaFromForm();const buf=await fetch('assets/plantilla_SCOF01.xlsx').then(r=>r.arrayBuffer()),wb=new ExcelJS.Workbook();await wb.xlsx.load(buf);const ws=wb.getWorksheet('Caja Menor'),m=state.meta,all=[...state.movements].sort((a,b)=>(a.date+a.createdAt).localeCompare(b.date+b.createdAt));ws.getCell('D5').value=m.placeDate;ws.getCell('D7').value=m.period;ws.getCell('I5').value=m.responsible;ws.getCell('I6').value=m.area;ws.getCell('I7').value=m.position;ws.getCell('I8').value=m.aircraft;ws.getCell('D10').value=m.cardNumber;ws.getCell('D11').value=+m.initialBalance||0;ws.getCell('D12').value=+m.secondDeposit||0;const t=totals();ws.getCell('D13').value=t.spent;ws.getCell('D14').value=t.balance;for(let r=20;r<=62;r++)for(const c of ['C','D','E','F','G','H','I','K'])ws.getCell(`${c}${r}`).value=null;all.slice(0,43).forEach((x,i)=>{const r=20+i;ws.getCell(`C${r}`).value=new Date(`${x.date}T00:00:00`);ws.getCell(`C${r}`).numFmt='dd/mm/yy';ws.getCell(`D${r}`).value=x.city;ws.getCell(`E${r}`).value=x.support;ws.getCell(`F${r}`).value=x.thirdParty;ws.getCell(`G${r}`).value=x.idType;ws.getCell(`H${r}`).value=x.idNumber;ws.getCell(`I${r}`).value=x.category;ws.getCell(`K${r}`).value=x.amount});ws.getCell('K63').value=t.spent;ws.getCell('C65').value='OBSERVACIONES:';ws.getCell('D65').value=m.observations;const out=await wb.xlsx.writeBuffer(),blob=new Blob([out],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`SIS_Caja_Menor_${m.aircraft||'SCOF01'}_${today()}.xlsx`;a.click();URL.revokeObjectURL(a.href);await archiveCurrent()}catch(e){alert('No fue posible generar el Excel: '+e.message)}};

function logoData(){return new Promise(ok=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=im.naturalWidth||300;c.height=im.naturalHeight||100;c.getContext('2d').drawImage(im,0,0);ok(c.toDataURL('image/png'))};im.onerror=()=>ok(null);im.src='assets/sis-logo.png'})}
function words(n){const u=['','UNO','DOS','TRES','CUATRO','CINCO','SEIS','SIETE','OCHO','NUEVE','DIEZ','ONCE','DOCE','TRECE','CATORCE','QUINCE','DIECISÉIS','DIECISIETE','DIECIOCHO','DIECINUEVE','VEINTE'],t=['','','VEINTE','TREINTA','CUARENTA','CINCUENTA','SESENTA','SETENTA','OCHENTA','NOVENTA'],h=['','CIENTO','DOSCIENTOS','TRESCIENTOS','CUATROCIENTOS','QUINIENTOS','SEISCIENTOS','SETECIENTOS','OCHOCIENTOS','NOVECIENTOS'];function p(x){x=Math.floor(x);if(x===0)return'CERO';if(x===100)return'CIEN';if(x<21)return u[x];if(x<100)return t[Math.floor(x/10)]+(x%10?' Y '+u[x%10]:'');if(x<1000)return h[Math.floor(x/100)]+(x%100?' '+p(x%100):'');if(x<1e6)return (Math.floor(x/1000)===1?'MIL':p(Math.floor(x/1000))+' MIL')+(x%1000?' '+p(x%1000):'');if(x<1e9)return (Math.floor(x/1e6)===1?'UN MILLÓN':p(Math.floor(x/1e6))+' MILLONES')+(x%1e6?' '+p(x%1e6):'');return String(x)}return p(Number(n)||0)}
function addHeader(doc,title,logo,page){if(logo)doc.addImage(logo,'PNG',12,8,32,10);doc.setFont('helvetica','bold');doc.setTextColor(15,39,66);doc.setFontSize(12);doc.text(title,105,14,{align:'center'});doc.setFontSize(7);doc.text(`SIS SOLUCIONES INTEGRALES · ${state.meta.aircraft||''} · Página ${page}`,198,14,{align:'right'});doc.setDrawColor(15,39,66);doc.line(12,20,198,20);doc.setTextColor(0)}
function fit(doc,text,x,y,w,max=2,size=7){doc.setFontSize(size);const lines=doc.splitTextToSize(String(text||''),w).slice(0,max);doc.text(lines,x,y)}
function drawScof(doc,all,logo){addHeader(doc,'CAJA MENOR - SCOF01',logo,1);doc.setFontSize(6.5);const m=state.meta,t=totals();const left=[['LUGAR Y FECHA',m.placeDate],['PERIODO',m.period],['TARJETA PEOPLE PASS',m.cardNumber],['Saldo inicial',money(m.initialBalance)],['2do depósito',money(m.secondDeposit)],['Gastos Caja Menor',money(t.spent)],['Saldo final',money(t.balance)]],right=[['NOMBRE RESPONSABLE',m.responsible],['ÁREA',m.area],['CARGO',m.position],['AERONAVE',m.aircraft]];let y=27;left.forEach((r,i)=>{doc.setFont('helvetica','bold');doc.text(r[0],12,y+i*6);doc.setFont('helvetica','normal');doc.text(String(r[1]||''),48,y+i*6)});right.forEach((r,i)=>{doc.setFont('helvetica','bold');doc.text(r[0],112,y+i*6);doc.setFont('helvetica','normal');doc.text(String(r[1]||''),151,y+i*6)});const xs=[12,32,57,84,111,133,153,176,199],heads=['FECHA','CIUDAD','SOPORTE','TERCERO','TIPO ID','NÚMERO ID','CONCEPTO','TOTAL'];y=72;doc.setFillColor(225,232,238);doc.rect(12,y,187,8,'F');for(let i=0;i<heads.length;i++){doc.rect(xs[i],y,xs[i+1]-xs[i],8);doc.setFont('helvetica','bold');doc.setFontSize(5);doc.text(heads[i],(xs[i]+xs[i+1])/2,y+5,{align:'center'})}y+=8;doc.setFont('helvetica','normal');for(const x of all.slice(0,28)){const vals=[fmtDate(x.date),x.city,x.support,x.thirdParty,x.idType,x.idNumber,x.category,money(x.amount)];for(let i=0;i<vals.length;i++){doc.rect(xs[i],y,xs[i+1]-xs[i],6);fit(doc,vals[i],xs[i]+1,y+4,xs[i+1]-xs[i]-2,1,4.8)}y+=6}while(y<246){for(let i=0;i<heads.length;i++)doc.rect(xs[i],y,xs[i+1]-xs[i],6);y+=6}doc.setFont('helvetica','bold');doc.text('TOTAL',170,255);doc.rect(176,250,23,7);doc.text(money(t.spent),198,255,{align:'right'});doc.setFontSize(5.5);doc.text('OBSERVACIONES:',12,264);doc.setFont('helvetica','normal');fit(doc,m.observations,40,264,157,3,5.5);doc.rect(12,260,187,15);doc.setFont('helvetica','bold');doc.text('INSTRUCCIONES',12,281);doc.setFont('helvetica','normal');fit(doc,'Anexar los documentos soporte de los gastos. Presentar la cuenta debidamente aprobada dentro del plazo establecido.',12,285,130,3,5);doc.rect(150,278,49,14);doc.setFont('helvetica','bold');doc.text('FIRMA / Vo.Bo. / APROBADA',174.5,284,{align:'center'})}
function drawReceipt(doc,x,y,w,h,item,num,logo){
  const green=[42,145,38], pale=[242,247,239], line=[120,112,58];
  doc.setDrawColor(...line);doc.setLineWidth(.28);doc.roundedRect(x,y,w,h,1.8,1.8);
  // Corporate mark and title
  if(logo)doc.addImage(logo,'PNG',x+3,y+2,23,7);
  doc.setFillColor(...green);doc.roundedRect(x+w-41,y+1,39,13,1.5,1.5,'F');
  doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(7.8);doc.text('RECIBO DE',x+w-21.5,y+6,{align:'center'});doc.text('CAJA MENOR',x+w-21.5,y+10.2,{align:'center'});
  doc.setTextColor(0);doc.setFontSize(5.2);
  const top=y+16, row1=8,row2=8, conceptH=Math.max(13,h*0.23), lettersH=Math.max(11,h*0.18), bottomH=14;
  // Date and number
  doc.rect(x,top,w,row1); const c1=x+w*.39,c2=x+w*.50,c3=x+w*.61,c4=x+w*.75;
  [c1,c2,c3,c4].forEach(xx=>doc.line(xx,top,xx,top+row1));
  doc.setFont('helvetica','bold');doc.text('CIUDAD',x+2,top+3.2);doc.text('DÍA',c1+1.5,top+3.2);doc.text('MES',c2+1.5,top+3.2);doc.text('AÑO',c3+1.5,top+3.2);doc.text('No.',c4+1.5,top+3.2);
  doc.setFont('helvetica','normal');fit(doc,item.city,x+2,top+6.6,c1-x-4,1,5.7);const d=new Date(item.date+'T00:00:00');doc.text(String(d.getDate()).padStart(2,'0'),c1+5,top+6.6);doc.text(String(d.getMonth()+1).padStart(2,'0'),c2+5,top+6.6);doc.text(String(d.getFullYear()),c3+4,top+6.6);doc.text(`RC-${String(num).padStart(3,'0')}`,c4+2,top+6.6);
  // Paid to / amount
  let yy=top+row1;doc.rect(x,yy,w,row2);doc.line(x+w*.72,yy,x+w*.72,yy+row2);doc.setFont('helvetica','bold');doc.text('PAGADO A',x+2,yy+3);doc.text('$',x+w*.74,yy+5.8);doc.setFont('helvetica','normal');fit(doc,item.thirdParty,x+2,yy+6.5,w*.68,1,6);doc.setFont('helvetica','bold');doc.setFontSize(6.4);doc.text(new Intl.NumberFormat('es-CO').format(item.amount),x+w-3,yy+5.8,{align:'right'});
  // Concept
  yy+=row2;doc.rect(x,yy,w,conceptH);doc.setFontSize(5.2);doc.setFont('helvetica','bold');doc.text('CONCEPTO',x+2,yy+3.2);doc.setFont('helvetica','normal');fit(doc,item.detail||item.category,x+2,yy+7,w-4,3,6);
  // Value in words
  yy+=conceptH;doc.setFillColor(...pale);doc.rect(x,yy,w,lettersH,'FD');doc.setFont('helvetica','bold');doc.setFontSize(5.2);doc.text('VALOR (EN LETRAS)',x+2,yy+3.2);doc.setFont('helvetica','normal');fit(doc,`${words(item.amount)} PESOS M/CTE`,x+2,yy+7,w-4,2,5.8);
  // Bottom fields
  yy+=lettersH;doc.rect(x,yy,w,bottomH);const leftW=w*.34;doc.line(x+leftW,yy,x+leftW,yy+bottomH);doc.line(x,yy+bottomH/2,x+leftW,yy+bottomH/2);
  doc.setFont('helvetica','bold');doc.setFontSize(5.1);doc.text('CÓDIGO',x+2,yy+3.8);doc.text('APROBADO',x+2,yy+bottomH/2+3.8);doc.text('FIRMA DE RECIBIDO',x+leftW+2,yy+3.8);
  const sigY=yy+bottomH-4;if(item.signature)doc.addImage(item.signature,'PNG',x+leftW+18,yy+1,w-leftW-22,bottomH-5);doc.line(x+leftW+2,sigY,x+w-2,sigY);
  doc.setFont('helvetica','normal');doc.setFontSize(4.8);const isNit=/nit|rut/i.test(item.idType||'');doc.text(isNit?'NIT:':'C.C.:',x+leftW+2,yy+bottomH-1.2);fit(doc,item.idNumber,x+leftW+13,yy+bottomH-1.2,w-leftW-16,1,5.2);
}
function receiptNumber(item){const sorted=[...state.movements].filter(x=>x.support==='Recibo de Caja').sort((a,b)=>(a.date+a.createdAt).localeCompare(b.date+b.createdAt));return Math.max(1,sorted.findIndex(x=>x.id===item.id)+1)}
function receiptHtml(item){
  const d=new Date(item.date+'T00:00:00'),num=receiptNumber(item),idLabel=/nit|rut/i.test(item.idType||'')?'NIT':'C.C.';
  return `<div class="receipt-paper"><div class="receipt-top"><div class="receipt-brand"><img src="assets/sis-logo.png" alt="SIS"></div><div class="receipt-title">RECIBO DE<br>CAJA MENOR</div></div><div class="receipt-grid"><div class="receipt-row receipt-date"><div><div class="receipt-label">Ciudad</div><div class="receipt-value">${safe(item.city)}</div></div><div><div class="receipt-label">Día</div><div class="receipt-value">${String(d.getDate()).padStart(2,'0')}</div></div><div><div class="receipt-label">Mes</div><div class="receipt-value">${String(d.getMonth()+1).padStart(2,'0')}</div></div><div><div class="receipt-label">Año</div><div class="receipt-value">${d.getFullYear()}</div></div><div><div class="receipt-label">No.</div><div class="receipt-value">RC-${String(num).padStart(3,'0')}</div></div></div><div class="receipt-row receipt-paid"><div><div class="receipt-label">Pagado a</div><div class="receipt-value">${safe(item.thirdParty)}</div></div><div><div class="receipt-label">Valor</div><div class="receipt-amount">${money(item.amount)}</div></div></div><div class="receipt-row receipt-one"><div><div class="receipt-label">Concepto</div><div class="receipt-value">${safe(item.detail||item.category)}</div></div></div><div class="receipt-row receipt-one receipt-words"><div><div class="receipt-label">Valor en letras</div><div class="receipt-value">${words(item.amount)} PESOS M/CTE</div></div></div><div class="receipt-row receipt-bottom"><div class="receipt-bottom-left"><div><div class="receipt-label">Código</div><div class="receipt-value"></div></div><div><div class="receipt-label">Aprobado</div><div class="receipt-value"></div></div></div><div class="receipt-signature"><div class="receipt-label">Firma de recibido</div>${item.signature?`<img src="${item.signature}" alt="Firma">`:'<div class="receipt-value receipt-missing">Falta firma</div>'}<div class="receipt-sign-line">${idLabel}: ${safe(item.idNumber)}</div></div></div></div></div>`;
}
function openReceiptPreview(id){
  const item=state.movements.find(x=>x.id===id);if(!item)return;
  if(item.support!=='Recibo de Caja')return alert('Este movimiento no corresponde a un Recibo de Caja.');
  previewReceiptId=id;$('#receiptPreview').innerHTML=receiptHtml(item);$('#receiptModal').classList.remove('hidden');
}
$('#closeReceipt').onclick=()=>$('#receiptModal').classList.add('hidden');
$('#receiptEdit').onclick=()=>{const id=previewReceiptId;$('#receiptModal').classList.add('hidden');openExpense(id)};
$('#receiptDownload').onclick=async()=>{
  const item=state.movements.find(x=>x.id===previewReceiptId);if(!item)return;
  if(!item.signature&&!confirm('Este recibo todavía no tiene firma. ¿Descargar de todas formas?'))return;
  const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4',compress:true}),logo=await logoData();
  addHeader(doc,'RECIBO DE CAJA MENOR',logo,1);drawReceipt(doc,15,32,180,125,item,receiptNumber(item),logo);
  doc.save(`Recibo_RC-${String(receiptNumber(item)).padStart(3,'0')}_${item.thirdParty||'SIS'}_${item.date}.pdf`);
};

async function imgDim(src){return new Promise(ok=>{const im=new Image();im.onload=()=>ok({w:im.width,h:im.height});im.src=src})}
$('#exportPdf').onclick=async()=>{if(!state.movements.length)return alert('No hay movimientos.');syncMetaFromForm();const missing=state.movements.filter(x=>(x.support==='Recibo de Caja'&&!x.signature)||(!x.attachments?.length&&x.support!=='Recibo de Caja'));if(missing.length&&!confirm(`Hay ${missing.length} movimiento(s) con firma o soporte pendiente. ¿Generar de todas formas?`))return;const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4',compress:true}),logo=await logoData(),all=[...state.movements].sort((a,b)=>(a.date+a.createdAt).localeCompare(b.date+b.createdAt));drawScof(doc,all,logo);let page=1,receipts=all.filter(x=>x.support==='Recibo de Caja');for(let i=0;i<receipts.length;){doc.addPage();addHeader(doc,'RECIBOS DE CAJA MENOR',logo,++page);const group=receipts.slice(i,i+4),three=group.some(x=>(x.detail||'').length>100),count=three?3:4,h=three?82:63;for(let j=0;j<count&&i<receipts.length;j++,i++){const col=j%2,row=Math.floor(j/2),x=10+col*96,y=26+row*(h+4);drawReceipt(doc,x,y,91,h,receipts[i],i+1,logo)}}for(const [idx,x] of all.entries()){for(const a of x.attachments||[]){for(let p=0;p<a.pages.length;p++){doc.addPage();addHeader(doc,`SOPORTE ${idx+1} - ${x.support.toUpperCase()}`,logo,++page);doc.setFont('helvetica','normal');doc.setFontSize(7);fit(doc,`${fmtDate(x.date)} | ${x.thirdParty||''} | ${x.detail||x.category} | ${money(x.amount)} | ${a.name}${a.pages.length>1?` - Página ${p+1}/${a.pages.length}`:''}`,12,28,186,2,7);const dim=await imgDim(a.pages[p]),ratio=Math.min(186/dim.w,250/dim.h),w=dim.w*ratio,h=dim.h*ratio;doc.addImage(a.pages[p],'JPEG',105-w/2,35,w,h,undefined,'FAST')}}}doc.save(`SIS_Caja_Menor_${state.meta.aircraft||'SCOF01'}_${today()}.pdf`);await archiveCurrent()};

async function renderHistory(){const box=$('#historyList'),items=(await getAll('boxes')).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));box.innerHTML=items.length?'':'<p class="muted">No hay cajas guardadas.</p>';for(const p of items){const spent=p.movements.reduce((s,x)=>s+(+x.amount||0),0),d=document.createElement('div');d.className='history-item';d.innerHTML=`<strong>${safe(p.meta.aircraft||'Sin aeronave')} · ${safe(p.meta.period||'Sin periodo')}</strong><small>${p.movements.length} movimientos · ${money(spent)} · ${new Date(p.updatedAt).toLocaleString('es-CO')}</small><div class="button-row"><button data-open>Abrir</button><button data-copy>Duplicar</button><button data-del class="danger">Eliminar</button></div>`;d.querySelector('[data-open]').onclick=async()=>{state=structuredClone(p);currentId=p.id;delete state.id;syncMetaToForm();await persistDraft();render();showView('homeView')};d.querySelector('[data-copy]').onclick=async()=>{state=structuredClone(p);delete state.id;currentId=null;state.meta.period='';state.movements=state.movements.map(x=>({...x,id:uid(),signature:null}));syncMetaToForm();await persistDraft();render();showView('homeView');toast('Caja duplicada')};d.querySelector('[data-del]').onclick=async()=>{if(confirm('¿Eliminar esta caja?')){await del('boxes',p.id);renderHistory()}};box.appendChild(d)}}
$('#refreshHistory').onclick=renderHistory;$('#filter').onchange=renderMovements;
$('#backup').onclick=async()=>{const payload={draft:state,history:await getAll('boxes')},blob=new Blob([JSON.stringify(payload)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`SIS_Caja_Menor_respaldo_${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#restore').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(p.draft){state=p.draft;await persistDraft()}for(const b of p.history||[])await put('boxes',null,b);syncMetaToForm();render();toast('Copia restaurada')}catch(err){alert('Copia inválida: '+err.message)}};

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}else alert('En iPhone: abra Compartir y pulse “Añadir a pantalla de inicio”.')};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
openDB().then(async()=>{const d=await get('draft','current');if(d)state=d;syncMetaToForm();render()}).catch(e=>alert('No se pudo iniciar el almacenamiento local: '+e.message));
